"""Seed do cadastro de produtos (estoque / grupos / unidades)."""

ESTOQUES_SEED = [
    'MATRIZ',
]

# codigo, descricao, unid_conversao, valor_conversao, nutrientes, uma, estoque, pratos, ativo
UNIDADES_SEED = [
    ('AM', '', '', 0, True, True, True, True, True),
    ('BB', 'BOMBONAS', '', 0, True, True, True, True, True),
    ('BD', 'BALDES', '', 0, True, True, True, True, True),
    ('CX', '', '', 0, True, True, True, True, True),
    ('G', 'GRAMA', 'KG', 0.001, True, True, True, True, True),
    ('KG', 'QUILOGRAMAS', 'G', 1000, True, True, True, True, True),
    ('L', 'LITROS', 'ML', 1000, True, True, True, True, True),
    ('LT', 'LITRO', 'ML', 1000, True, True, True, True, True),
    ('MCG', 'MICROGRAMA', '', 0, True, True, True, True, True),
    ('MG', 'MILIGRAMA', 'G', 0.001, True, True, True, True, True),
    ('ML', 'MILILITROS', 'L', 0.001, True, True, True, True, True),
    ('MOL', 'MOLHOS', 'ML', 0.2, True, True, True, True, True),
    ('NC', 'NC', '', 0, True, True, True, True, True),
    ('PC', '', '', 0, False, False, False, False, True),
    ('PCT', 'PACOTES', 'G', 0, True, True, True, True, True),
    ('PT', '', '', 0, False, False, False, False, True),
    ('RL', 'ROLO', '', 0, False, False, False, False, True),
    ('SC', '', '', 0, False, False, False, False, True),
    ('UN', 'UNIDADES', 'PCT', 0, True, True, True, True, True),
]

GRUPOS_PRODUTO_SEED = [
    'BEBIDAS',
    'CARNES',
    'CESTA BÁSICA',
    'DEDETIZAÇÃO',
    'DESCARTÁVEIS',
    'DIETAS',
    'DIVERSOS',
    'ENTERAL',
    'EPI',
    'EQUIPAMENTOS',
    'ESTOCÁVEIS',
    'GÁS',
    'HORTI-FRUTTI',
    'LABORATÓRIO',
    'LACTICÍNIOS',
    'LEITES',
    'LIMPEZA',
    'LOCAÇÕES',
    'MANUTENÇÃO',
    'MAT. ESCRITORIO',
    'MÓDULOS',
    'N.C.',
    'NI',
    'PADARIA',
    'PEIXES',
    'POLPAS',
    'SUPLEMENTOS',
    'TELEFONIA',
    'TRIBUTOS',
    'UNIFORMES',
    'UTENSÍLIOS',
]

# estoque, grupo, codigo, descricao, qtd, un, preco_med, ult_preco, min, max, qtd_liq, un_liq, fc
PRODUTOS_SEED = [
    ('MATRIZ', 'BEBIDAS', 'ACHOCO', 'ACHOCOLATADO 200 ML', 0, 'UN', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'AGU1500', 'AGUA 1500', 0, 'L', 0.01, 0.01, 0, 0, 0, 'NC', True),
    ('MATRIZ', 'BEBIDAS', 'AGU200', 'AGUA MINERAL 200 ML', 0, 'UN', 0.01, 0.01, 0, 0, 0, 'NC', True),
    ('MATRIZ', 'BEBIDAS', 'AGU510', 'AGUA MINERAL 510 ML', 0, 'L', 0.01, 0.01, 0, 0, 0, 'NC', True),
    ('MATRIZ', 'BEBIDAS', 'BEBLACVIT', 'BEBIDA LACTEA VITAMINA', 0, 'UN', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'COCA2L', 'COCA COLA 2L', 0, 'L', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'COLORA', 'CLOROFILA', 0, 'KG', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'GATORA', 'GATORADE', 0, 'UN', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'GUAR2L', 'GUARANA DIET 2L', 0, 'L', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'LEIUAT', 'LEITE UAT ITAMBYN', 0, 'L', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'MANGO', 'SUCO DE MORANGO 200 ML TP', 0, 'UN', 0.01, 0.01, 0, 0, 0, 'NC', True),
    ('MATRIZ', 'BEBIDAS', 'MATCHA', 'MATE 200', 0, 'ML', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'REFCOCA', 'REFRIGERANTE COCA COLA', 0, 'L', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'SABA1,0L', 'SUCO DE ABACAXI 1,0 L', 0, 'L', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'BEBIDAS', 'SUCLAR', 'SUCO DE LARANJA 200 ML', 0, 'UN', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'ESTOCÁVEIS', 'SALI240', 'SAL INDIVIDUAL', 0, 'PCT', 0.01, 0.01, 1, 10, 0, 'NC', False),
    ('MATRIZ', 'ESTOCÁVEIS', 'SALREF', 'SAL REFINADO', 0, 'KG', 0.01, 0.01, 30, 200, 0, 'NC', False),
    ('MATRIZ', 'ESTOCÁVEIS', 'SACLIX', 'SACO DE LIXO 100 L', 0, 'UN', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'ESTOCÁVEIS', 'SAP100', 'SAPATILHA DESCARTAVEL', 0, 'PCT', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'ESTOCÁVEIS', 'SUKCHO', 'SUSTAGEM CHOCOLATE', 0, 'UN', 0.01, 0.01, 0, 0, 0, 'NC', False),
    ('MATRIZ', 'ESTOCÁVEIS', 'TAPIOC', 'TAPIOCA', 0, 'KG', 0.01, 0.01, 0, 0, 0, 'NC', False),
]
