"""Seed do cadastro nutricional (tabela de nutrientes)."""

NUTRIENTES_PADRAO = [
    ('Energia', 'kcal', 1),
    ('Proteína', 'g', 1),
    ('Lipídios', 'g', 1),
    ('Carboidrato', 'g', 1),
    ('Fibra alimentar', 'g', 1),
    ('Cálcio', 'mg', 1),
    ('Ferro', 'mg', 1),
    ('Sódio', 'mg', 1),
    ('Potássio', 'mg', 1),
    ('Vitamina C', 'mg', 1),
]

# tabela, alimento, macros, nutrientes[(nome, qtd, un, fator)]
ALIMENTOS_SEED = [
    {
        'tabela': 'Tabela Padrão',
        'nome': 'ARROZ BRANCO COZIDO',
        'cal_carboidratos': 164,
        'cal_gordura': 2,
        'cal_proteina': 10,
        'cal_total': 176,
        'qtd_carboidratos': 40.9,
        'qtd_gordura': 0.2,
        'qtd_proteina': 2.5,
        'ref_consumo': '100 g',
        'coeficiente_npu': 0.7,
        'gluten': False,
        'fenilalanina': False,
        'nutrientes': [
            ('Energia', 128, 'kcal', 1),
            ('Proteína', 2.5, 'g', 1),
            ('Lipídios', 0.2, 'g', 1),
            ('Carboidrato', 28.1, 'g', 1),
            ('Fibra alimentar', 1.6, 'g', 1),
            ('Cálcio', 4, 'mg', 1),
            ('Ferro', 0.3, 'mg', 1),
            ('Sódio', 1, 'mg', 1),
            ('Potássio', 25, 'mg', 1),
            ('Vitamina C', 0, 'mg', 1),
        ],
    },
    {
        'tabela': 'Tabela Padrão',
        'nome': 'FEIJÃO CARIOCA COZIDO',
        'cal_carboidratos': 56,
        'cal_gordura': 5,
        'cal_proteina': 19,
        'cal_total': 80,
        'qtd_carboidratos': 14.0,
        'qtd_gordura': 0.5,
        'qtd_proteina': 4.8,
        'ref_consumo': '100 g',
        'coeficiente_npu': 0.6,
        'gluten': False,
        'fenilalanina': False,
        'nutrientes': [
            ('Energia', 76, 'kcal', 1),
            ('Proteína', 4.8, 'g', 1),
            ('Lipídios', 0.5, 'g', 1),
            ('Carboidrato', 13.6, 'g', 1),
            ('Fibra alimentar', 8.5, 'g', 1),
            ('Cálcio', 27, 'mg', 1),
            ('Ferro', 1.3, 'mg', 1),
            ('Sódio', 2, 'mg', 1),
            ('Potássio', 255, 'mg', 1),
            ('Vitamina C', 0, 'mg', 1),
        ],
    },
    {
        'tabela': 'Tabela Padrão',
        'nome': 'PEITO DE FRANGO GRELHADO',
        'cal_carboidratos': 0,
        'cal_gordura': 32,
        'cal_proteina': 128,
        'cal_total': 160,
        'qtd_carboidratos': 0,
        'qtd_gordura': 3.6,
        'qtd_proteina': 32.0,
        'ref_consumo': '100 g',
        'coeficiente_npu': 0.9,
        'gluten': False,
        'fenilalanina': False,
        'nutrientes': [
            ('Energia', 159, 'kcal', 1),
            ('Proteína', 32.0, 'g', 1),
            ('Lipídios', 3.6, 'g', 1),
            ('Carboidrato', 0, 'g', 1),
            ('Fibra alimentar', 0, 'g', 1),
            ('Cálcio', 8, 'mg', 1),
            ('Ferro', 0.5, 'mg', 1),
            ('Sódio', 63, 'mg', 1),
            ('Potássio', 318, 'mg', 1),
            ('Vitamina C', 0, 'mg', 1),
        ],
    },
    {
        'tabela': 'Tabela Padrão',
        'nome': 'PÃO FRANCÊS',
        'cal_carboidratos': 234,
        'cal_gordura': 28,
        'cal_proteina': 32,
        'cal_total': 294,
        'qtd_carboidratos': 58.6,
        'qtd_gordura': 3.1,
        'qtd_proteina': 8.0,
        'ref_consumo': '50 g',
        'coeficiente_npu': 0.5,
        'gluten': True,
        'fenilalanina': False,
        'nutrientes': [
            ('Energia', 300, 'kcal', 1),
            ('Proteína', 8.0, 'g', 1),
            ('Lipídios', 3.1, 'g', 1),
            ('Carboidrato', 58.6, 'g', 1),
            ('Fibra alimentar', 2.3, 'g', 1),
            ('Cálcio', 16, 'mg', 1),
            ('Ferro', 1.5, 'mg', 1),
            ('Sódio', 648, 'mg', 1),
            ('Potássio', 116, 'mg', 1),
            ('Vitamina C', 0, 'mg', 1),
        ],
    },
    {
        'tabela': 'Tabela Padrão',
        'nome': 'BANANA PRATA',
        'cal_carboidratos': 90,
        'cal_gordura': 1,
        'cal_proteina': 5,
        'cal_total': 96,
        'qtd_carboidratos': 22.8,
        'qtd_gordura': 0.1,
        'qtd_proteina': 1.3,
        'ref_consumo': '1 unidade',
        'coeficiente_npu': 0.4,
        'gluten': False,
        'fenilalanina': False,
        'nutrientes': [
            ('Energia', 98, 'kcal', 1),
            ('Proteína', 1.3, 'g', 1),
            ('Lipídios', 0.1, 'g', 1),
            ('Carboidrato', 26.0, 'g', 1),
            ('Fibra alimentar', 2.0, 'g', 1),
            ('Cálcio', 3, 'mg', 1),
            ('Ferro', 0.3, 'mg', 1),
            ('Sódio', 0, 'mg', 1),
            ('Potássio', 376, 'mg', 1),
            ('Vitamina C', 9, 'mg', 1),
        ],
    },
]
