"""Seed do cadastro de etiquetas."""

ETIQUETAS_SEED = [
    {
        'nome': '1 - PIMACO 6080 (7PT)',
        'ativa': True,
        'tamanho_folha': 'carta',
        'folha_altura_mm': 279.4,
        'folha_largura_mm': 215.9,
        'orientacao': 'retrato',
        'margem_esquerda': 4.8,
        'margem_direita': 4.8,
        'margem_superior': 12.7,
        'margem_inferior': 12.7,
        'num_colunas': 3,
        'dist_colunas_mm': 3.1,
        'altura_etiqueta_mm': 25.4,
        'tamanho_fonte': 7,
        'campos': [
            {'tipo': 'D', 'nome': 'PACIENTE', 'texto': 'Nome do paciente'},
            {'tipo': 'D', 'nome': 'DIETA', 'texto': 'Dieta prescrita'},
            {'tipo': 'D', 'nome': 'LEITO', 'texto': 'Leito'},
            {'tipo': 'D', 'nome': 'DATA', 'texto': 'Data/hora'},
            {'tipo': 'F', 'nome': 'FORMULA', 'texto': 'Fórmula'},
            {'tipo': 'F', 'nome': 'VOLUME', 'texto': 'Volume (ml)'},
        ],
    },
    {
        'nome': '2 - PIMACO 6180 (8PT)',
        'ativa': True,
        'tamanho_folha': 'carta',
        'folha_altura_mm': 279.4,
        'folha_largura_mm': 215.9,
        'orientacao': 'retrato',
        'margem_esquerda': 5.0,
        'margem_direita': 5.0,
        'margem_superior': 12.7,
        'margem_inferior': 12.7,
        'num_colunas': 3,
        'dist_colunas_mm': 3.0,
        'altura_etiqueta_mm': 25.4,
        'tamanho_fonte': 8,
        'campos': [
            {'tipo': 'D', 'nome': 'PACIENTE', 'texto': 'Nome do paciente'},
            {'tipo': 'D', 'nome': 'DIETA', 'texto': 'Dieta prescrita'},
            {'tipo': 'D', 'nome': 'CLINICA', 'texto': 'Clínica'},
        ],
    },
    {
        'nome': '3 - A4 PERSONALIZADA',
        'ativa': False,
        'tamanho_folha': 'a4',
        'folha_altura_mm': 297,
        'folha_largura_mm': 210,
        'orientacao': 'retrato',
        'margem_esquerda': 10,
        'margem_direita': 10,
        'margem_superior': 10,
        'margem_inferior': 10,
        'num_colunas': 2,
        'dist_colunas_mm': 5,
        'altura_etiqueta_mm': 40,
        'tamanho_fonte': 9,
        'campos': [
            {'tipo': 'D', 'nome': 'PACIENTE', 'texto': 'Paciente'},
            {'tipo': 'F', 'nome': 'FORMULA', 'texto': 'Fórmula enteral'},
        ],
    },
]
