"""Seed do cadastro de cardápios (exemplos da tela legado)."""

CARDAPIO_OPCOES = {
    'grupos': ['PRINCIPAL', 'ALTERNATIVO', 'FESTIVO'],
    'dias_semana': ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    'acompanhamentos': [
        'ARROZ S/ SAL', 'ARROZ C/ SAL', 'ARROZ INTEGRAL', 'PURÊ DE BATATA', 'MACARRÃO',
    ],
    'pratos_base': [
        'ISCA DE CARNE AO MOLHO FERRUGEM', 'ISCA DE CARNE MOIDA NO FORNO/ALM',
        'BIFE ACEBOLADO', 'FRANGO GRELHADO', 'PEIXE ASSADO',
    ],
    'proteinas_opcionais': [
        'ISCA DE FRANGO S/ SAL', 'ISCA DE FRANGO C/ SAL', 'OVO MEXIDO', 'QUEIJO BRANCO', 'ATUM',
    ],
    # alias legado
    'proteicos_opcionais': [
        'ISCA DE FRANGO S/ SAL', 'ISCA DE FRANGO C/ SAL', 'OVO MEXIDO', 'QUEIJO BRANCO', 'ATUM',
    ],
    'guarnicoes': [
        'BATATA REFOG. S/ SAL', 'BATATA DOCE C/ SAL', 'LEGUMES REFOGADOS', 'FAROFÁ', 'FEIJÃO',
    ],
    'sobremesas': [
        'MAÇÃ COZ À FRANC.', 'MACA COZ C/ ADO', 'BANANA', 'CREME DE BANANA', 'GELATINA', 'PUDIM',
    ],
    'frutas': [
        'MAÇÃ', 'BANANA', 'MAMÃO', 'MELÃO', 'LARANJA', 'MATE GELADO',
    ],
    'sucos': [
        'SUCO DE LARANJA', 'SUCO DE MARACUJÁ', 'SUCO DE GOIABA', 'ÁGUA',
    ],
    'vitaminas_sucos': [
        'VIT. MAÇÃ C/ L. INTEG.', 'CHUCHU REFOG. C/ SAL', 'CHUCHU REFOG. S/ SAL',
        'SOPA DE LEGUMES', 'CALDO VERDE',
    ],
    'docinhos_saladas': [
        'SALADA CRUA', 'DOCINHO', '',
    ],
    'bebidas': [
        'MATE GELADO', 'CAFÉ C/ LEITE S/ AÇÚC.', 'VIT. MAÇÃ C/ L. INTEG.', 'SUCO DE LARANJA', 'ÁGUA',
    ],
    'entradas_sopas': [
        'CHUCHU REFOG. S/ SAL', 'SOPA DE LEGUMES', 'SALADA CRUA', 'CALDO VERDE',
    ],
    'outros': [
        'ADOÇANTE IND.', 'ADOÇANTE PO', 'AÇÚCAR IND.', 'SAL', 'AZEITE',
    ],
    'pratos_pequenos': [
        'PÃO CARECA SAL', 'MANTEIGA IND.', 'QUEIJO MINAS', 'AÇÚCAR IND.',
        'PÃO FRANCÊS', 'BISCOITO ÁGUA E SAL', 'IOGURTE',
    ],
    'principais_liquidos': [
        'GELÉIA DE MOCOTÓ', 'CALDO DE CARNE', 'SOPA CREME', 'MINGAU',
    ],
    'organizar_opcoes': [
        'Ord, Dieta, Horário',
        'Ord, Horário, Dieta',
        'Dieta, Ord, Horário',
        'Dieta, Horário, Ord',
        'Horário, Ord, Dieta',
        'Horário, Dieta, Ord',
    ],
}

# Exemplos da foto + cardápios por horário (Substituições / mapa)
CARDAPIOS_SEED = [
    {
        'tipo': 'grandes',
        'grupo_cardapio': 'PRINCIPAL',
        'dia_mes': 1,
        'dia_semana': 'Domingo',
        'dieta': 'BRANDA CONSTIPANTE HDDS',
        'hr_almoco': True,
        'hr_jantar': True,
        'itens': {
            'entrada_tipo': 'Salada',
            'proteina_tipo': 'Aves',
            'acompanhamento': 'ARROZ S/ SAL',
            'prato_base': 'ISCA DE CARNE AO MOLHO FERRUGEM',
            'proteina_opcional': 'ISCA DE FRANGO S/ SAL',
            'guarnicao': 'BATATA REFOG. S/ SAL',
            'docinho_salada': '',
            'sobremesa': 'MAÇÃ COZ À FRANC.',
            'fruta': 'MATE GELADO',
            'suco': '',
            'vitamina_suco': 'CHUCHU REFOG. S/ SAL',
            'outros': 'ADOÇANTE IND.',
        },
        'vet': 0,
        'custo': 0,
        'organizar_por': 'Ord, Dieta, Horário',
        'usuario_alteracao': 'silvana',
    },
    {
        'tipo': 'pequenas',
        'grupo_cardapio': 'PRINCIPAL',
        'dia_mes': 1,
        'dia_semana': 'Domingo',
        'dieta': 'BRANDA',
        'hr_desjejum': True,
        'itens': {
            'bebida': 'CAFÉ C/ LEITE S/ AÇÚC.',
            'prato1': 'BROA C/ GERGELIM',
            'prato2': 'MANTEIGA IND. S/ SAL',
            'prato3': 'PASTA DE RICOTA',
            'prato4': 'AÇÚCAR IND.',
            'prato5': '',
            'prato6': '',
            'prato7': '',
            'sobremesa': 'MAÇÃ',
        },
        'vet': 0,
        'custo': 0,
        'organizar_por': 'Ord, Dieta, Horário',
        'usuario_alteracao': 'silvana',
    },
    {
        'tipo': 'pequenas',
        'grupo_cardapio': 'PRINCIPAL',
        'dia_mes': 1,
        'dia_semana': 'Domingo',
        'dieta': 'BRANDA',
        'hr_colacao': True,
        'itens': {
            'bebida': '',
            'prato1': 'MELÃO',
            'prato2': '',
            'prato3': '',
            'prato4': '',
            'prato5': '',
            'prato6': '',
            'prato7': '',
            'sobremesa': '',
        },
        'vet': 0,
        'custo': 0,
        'organizar_por': 'Ord, Dieta, Horário',
        'usuario_alteracao': 'silvana',
    },
    {
        'tipo': 'pequenas',
        'grupo_cardapio': 'PRINCIPAL',
        'dia_mes': 1,
        'dia_semana': 'Domingo',
        'dieta': 'BRANDA',
        'hr_almoco': True,
        'itens': {
            'bebida': 'SUCO DE MARACUJÁ',
            'prato1': 'LARANJA',
            'prato2': '',
            'prato3': '',
            'prato4': '',
            'prato5': '',
            'prato6': '',
            'prato7': '',
            'sobremesa': '',
        },
        'vet': 0,
        'custo': 0,
        'organizar_por': 'Ord, Dieta, Horário',
        'usuario_alteracao': 'silvana',
    },
    {
        'tipo': 'pequenas',
        'grupo_cardapio': 'PRINCIPAL',
        'dia_mes': 1,
        'dia_semana': 'Domingo',
        'dieta': 'BRANDA',
        'hr_merenda': True,
        'itens': {
            'bebida': 'CAFÉ C/ LEITE S/ AÇÚC.',
            'prato1': 'BROA DE MILHO',
            'prato2': 'MANTEIGA IND. S/ SAL',
            'prato3': 'PASTA DE RICOTA',
            'prato4': 'AÇÚCAR IND.',
            'prato5': '',
            'prato6': '',
            'prato7': '',
            'sobremesa': 'BANANA',
        },
        'vet': 0,
        'custo': 0,
        'organizar_por': 'Ord, Dieta, Horário',
        'usuario_alteracao': 'silvana',
    },
    {
        'tipo': 'pequenas',
        'grupo_cardapio': 'PRINCIPAL',
        'dia_mes': 1,
        'dia_semana': 'Domingo',
        'dieta': 'BRANDA',
        'hr_jantar': True,
        'itens': {
            'bebida': 'SUCO DE GOIABA',
            'prato1': 'FLAN',
            'prato2': '',
            'prato3': '',
            'prato4': '',
            'prato5': '',
            'prato6': '',
            'prato7': '',
            'sobremesa': '',
        },
        'vet': 0,
        'custo': 0,
        'organizar_por': 'Ord, Dieta, Horário',
        'usuario_alteracao': 'silvana',
    },
    {
        'tipo': 'pequenas',
        'grupo_cardapio': 'PRINCIPAL',
        'dia_mes': 1,
        'dia_semana': 'Domingo',
        'dieta': 'BRANDA',
        'hr_ceia': True,
        'itens': {
            'bebida': 'CAFÉ C/ LEITE S/ AÇÚC.',
            'prato1': 'PÃO SUÍÇO',
            'prato2': 'MANTEIGA IND. S/ SAL',
            'prato3': 'AÇÚCAR IND.',
            'prato4': '',
            'prato5': '',
            'prato6': '',
            'prato7': '',
            'sobremesa': '',
        },
        'vet': 0,
        'custo': 0,
        'organizar_por': 'Ord, Dieta, Horário',
        'usuario_alteracao': 'silvana',
    },
    {
        'tipo': 'liquidas',
        'grupo_cardapio': 'PRINCIPAL',
        'dia_mes': 1,
        'dia_semana': 'Domingo',
        'dieta': 'DIETA LÍQUIDA COMPLETA',
        'hr_desjejum': True,
        'itens': {
            'principal': 'GELÉIA DE MOCOTÓ',
            'bebida': 'VIT. MAÇÃ C/ L. INTEG.',
            'sobremesa': 'CREME DE BANANA',
            'gelado': 'MATE GELADO',
            'outros': 'AÇÚCAR IND.',
            'conv_bebida_coluna': '',
            'conv_bebida_quant': '',
            'conv_gelado_coluna': '',
            'conv_gelado_quant': '',
        },
        'vet': 0,
        'custo': 0,
        'organizar_por': 'Ord, Dieta, Horário',
        'usuario_alteracao': 'silvana',
    },
]
